version: '3.8'

services:
  movie_web_bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./:/home/node/app
    container_name: mw-bot
    command: yarn docker:start