name: Linting and Testing

on:
  push:
    branches:
      - master
      - dev
  pull_request:

jobs:
  linting:
    name: Run Linters
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        
    - name: Install dependencies
      run: pnpm install
      
    - name: Run ESLint
      run: pnpm lint

  building:
    name: Build project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
  
    - name: Install dependencies
      run: pnpm install

    - name: Build Project
      run: pnpm build
